In [395]:
import pandas as pd

In [396]:
EVENT_NAMES = ['COMPOUND WOMEN INDIVIDUAL',
 'RECURVE MEN INDIVIDUAL',
 'RECURVE WOMEN INDIVIDUAL',
 'COMPOUND MEN INDIVIDUAL',
 'COMPOUND MIXED TEAM',
 'RECURVE MIXED TEAM',
 'RECURVE MEN TEAM',
 'COMPOUND MEN TEAM',
 'RECURVE WOMEN TEAM',
 'COMPOUND WOMEN TEAM',
 'INDIAN ROUND WOMEN TEAM',
 'INDIAN ROUND WOMEN INDIVIDUAL',
 'INDIAN ROUND MEN INDIVIDUAL',
 'INDIAN ROUND MEN TEAM',
 'INDIAN ROUND MIXED TEAM',
 'RECURVE MEN',
 'RECURVE WOMEN',
 'COMPOUND MEN',
 'COMPOUND WOMEN',
 'INDIAN ROUND MEN',
 'INDIAN ROUND WOMEN',
 'RECURVE MIX TEAM',
 'COMPOUND MIX TEAM',
 'INDIAN ROUND MIX TEAM']

ROUND_NAMES = ['1/4 ELIMINATION',
 '1/4 FINAL',
 '1/8 ELIMINATION',
 '1/8 FINAL',
 'BRONZE MEDAL',
 'BRONZE MEDAL MATCH',
 'DATA NOT AVAILABLE',
 'FINAL',
 'GOLD MEDAL MATCH',
 'PRELIMINARY ROUND',
 'QUARTER-FINAL',
 'QUARTERFINAL',
 'ROUND 1',
 'ROUND 2',
 'ROUND OF 12',
 'ROUND OF 16',
 'ROUND OF 24',
 'ROUND OF 32',
 'ROUND OF 48',
 'ROUND OF 64',
 'ROUND OF 8',
 'SEMI-FINAL',
 'SEMIFINAL']


COUNTRY__CODES = {
    # Already codes (keep as-is)
    "KOR": "KOR", "KAZ": "KAZ", "INA": "IDN", "JPN": "JPN",
    "HKG": "HKG", "VIE": "VNM", "NEP": "NPL", "SRI": "LKA",
    "TPE": "TPE", "MYA": "MMR", "QAT": "QAT", "MAS": "MYS",
    "MGL": "MNG", "KSA": "SAU", "IND": "IND", "THA": "THA",
    "BAN": "BGD", "PRK": "PRK", "CHN": "CHN", "SGP": "SGP",
    "PHI": "PHL", "KGZ": "KGZ", "TJK": "TJK", "BHU": "BTN",
    "IRI": "IRN",

    # Full names → ISO3
    "South Korea": "KOR",
    "North Korea": "PRK",
    "India": "IND",
    "China": "CHN",
    "Japan": "JPN",
    "Indonesia": "IDN",
    "Malaysia": "MYS",
    "Iran": "IRN",
    "Kazakhstan": "KAZ",
    "Philippines": "PHL",
    "Thailand": "THA",
    "Hong Kong": "HKG",
    "Chinese Taipei": "TPE",
    
    
    "Mongolia": "MNG",
    "Bangladesh": "BGD",
    "Bhutan": "BTN",
    "Vietnam": "VNM",
    
    "Ukraine": "UKR",
    "Ivory Coast": "CIV",
    "Italy": "ITA",
    "Cuba": "CUB",
    "France": "FRA",
    "Chile": "CHL",
    "Brazil": "BRA",
    "Tonga": "TON",
    "Spain": "ESP",
    "Egypt": "EGY",
    "Germany": "DEU",
    "Colombia": "COL",
    "Netherlands": "NLD",
    "Slovakia": "SVK",
    "Venezuela": "VEN",
    "Great Britain": "GBR",
    "Australia": "AUS",
    "United States": "USA",
    "Libya": "LBY",
    "Belgium": "BEL",
    "Greece": "GRC",
    "Mexico": "MEX",
    
     "Zimbabwe": "ZWE",
    "Fiji": "FJI",
    "Nepal": "NPL",
    "Belarus": "BLR",
    "Malawi": "MWI",
    "Finland": "FIN",
    "Norway": "NOR",
    "Canada": "CAN",
    "GER": "DEU",
    "Kenya": "KEN",
    "Georgia": "GEO",
    "Russia": "RUS",
    
    "Denmark": "DNK",
    "Estonia": "EST",
    "Turkey": "TUR",
    "Israel": "ISR",
    "Romania": "ROU",
    "Moldova": "MDA",
    "Tunisia": "TUN",
    "Sweden": "SWE",
    "Slovenia": "SVN",
    "Hungary": "HUN",
    "Poland": "POL",
    "Virgin Islands": "VIR",
    "Luxembourg": "LUX",
    "Chad": "TCD",
    "Ecuador": "ECU",
    "Czech Republic": "CZE",
    
    "Puerto Rico": "PRI",
    "San Marino": "SMR",
    "Austria": "AUT",
    "Uzbekistan": "UZB",
    "Azerbaijan": "AZE",
    "Argentina": "ARG",
    "Guinea": "GIN",
    "El Salvador": "SLV",
    "South Africa": "ZAF"
}

# Junior 2023

In [397]:
from typing import DefaultDict
from collections import defaultdict


junior_2023_player_info = DefaultDict(list)

In [398]:
df_1 = pd.read_csv('Junior 2023/junior_2023_player_info_1.csv') 
df_2 = pd.read_csv('Junior 2023/junior_2023_player_info_2.csv') 
df_3 = pd.read_csv('Junior 2023/junior_2023_player_info_3.csv')

In [399]:
df_1['event_name'] = df_1['event_name'].str.replace('MEDAL TALLY - ','')

In [400]:
## Event Name Standardization
df_1['dob_1'] = pd.to_datetime(df_1['dob'],format='%d.%m.%Y')

In [401]:
df_1['dob'] = df_1['dob_1']

In [402]:
df_1 = df_1[['event_name','name','dob','state/unit']]

In [403]:
df_1['name'] = df_1['name'].str.strip().str.upper()
df_1['state/unit'] = df_1['state/unit'].str.strip().str.upper()

In [404]:
for _, row in df_1.iterrows():
    junior_2023_player_info[row['name']].append({
        'event_name': row['event_name'],
        'dob': row['dob'],
        'state/unit': row['state/unit'],
        'name': row['name']
    })

In [405]:
df_2['event_name'] = df_2['event_name'].str.replace('43rd NTPC Junior National(M&W) Archery Championship -','')

In [406]:
df_2['event_name'] = df_2['event_name'].str.strip()

In [407]:
df_2['name'] = df_2['name'].str.strip().str.upper()

In [408]:
df_2['state_unit'] = df_2['state_unit'].str.strip().str.upper()

In [409]:
df_2['name'] = df_2['name'].str.strip().str.upper()

In [410]:
for _,row in df_2.iterrows():
    junior_2023_player_info[row['name']].append({
        'event_name': row['event_name'],
        'dob': None,
        'state/unit': row['state_unit'],
        'name': row['name']
    })

In [411]:
df_3['event_name'] = df_3['event_name'].str.replace('43rd NTPC Junior National(M&W) Archery Championship -','').str.strip().str.upper()

In [412]:
df_3['name'] = df_3['name'].str.strip().str.upper()
df_3['state_unit'] = df_3['state_unit'].str.strip().str.upper()
df_3['dob'] = pd.to_datetime(df_3['dob'],format='%d.%m.%Y',errors='coerce')

In [413]:
for _, row in df_3.iterrows():
    junior_2023_player_info[row['name']].append({
        'event_name': row['event_name'],
        'dob': row['dob'],
        'state/unit': row['state_unit'],
        'name': row['name']
    })

# Junior 2025

In [414]:
junior_2025_player_info = DefaultDict(list)

In [415]:
df_1 = pd.read_csv('Junior 2025/junior_2025_player_info_1.csv')
df_2 = pd.read_csv('Junior 2025/junior_2025_player_info_2.csv')
df_3 = pd.read_csv('Junior 2025/junior_2025_player_info_3.csv')

In [416]:
df_1['event_name'] = df_1['event_name'].str.replace('MEDAL TALLY - ','').str.strip().str.upper()
df_1['name'] = df_1['name'].str.strip().str.upper()
df_1['dob'] = pd.to_datetime(df_1['dob'],format='%d.%m.%Y',errors='coerce') 
df_1['state/unit'] = df_1['state/unit'].str.strip().str.upper()
df_1 = df_1[['event_name','name','dob','state/unit']]

In [417]:
for _, row in df_1.iterrows():
    junior_2025_player_info[row['name']].append({
        'event_name': row['event_name'],
        'dob': row['dob'],
        'state/unit': row['state/unit'],
        'name': row['name']
    })

In [418]:
df_2['event_name'] = df_2['event_name'].str.replace('MEDAL TALLY - ','').str.strip().str.upper()
df_2['name'] = df_2['name'].str.strip().str.upper()
df_2['dob'] = None
df_2['state/unit'] = df_2['state/unit'].str.strip().str.upper()
df_2 = df_2[['event_name','name','dob','state/unit']]

In [419]:
for _, row in df_2.iterrows():
    junior_2025_player_info[row['name']].append({
        'event_name': row['event_name'],
        'dob': None,
        'state/unit': row['state/unit'],
        'name': row['name']
    })

In [420]:
df_3['event_name'] = df_3['event_name'].str.replace('43rd NTPC Junior National(M&W) Archery Championship -','').str.upper().str.strip()
df_3['name'] = df_3['name'].str.strip().str.upper()
df_3['state/unit'] = df_3['state/unit'].str.strip().str.upper()
df_3['dob'] = pd.to_datetime(df_3['dob'],format='%d.%m.%Y',errors='coerce')

In [421]:
for _, row in df_3.iterrows():
    junior_2025_player_info[row['name']].append({
        'event_name': row['event_name'],
        'dob': row['dob'],
        'state/unit': row['state/unit'],
        'name': row['name']
    })

# Senior 2024

In [422]:
senior_dec_2024_player_info = DefaultDict(list)

In [423]:
df_1 = pd.read_csv('/home/ashish-1221/archery_scrapping/archercy_scrapping/results/PDFs/Senior Dec 2024/senior_dec_2024_players_info_v1.csv')
df_2 = pd.read_csv('/home/ashish-1221/archery_scrapping/archercy_scrapping/results/PDFs/Senior Dec 2024/senior_dec_2024_players_info_v2.csv')
# df_3 = pd.read_csv('/home/ashish-1221/archery_scrapping/archercy_scrapping/results/PDFs/Senior Dec 2024/senior_dec_2024_player_info_3.csv')

In [424]:
df_1['event_name'] = df_1['event_name'].str.replace('MEDAL TALLY','').str.strip().str.upper()
df_1['name'] = df_1['name'].str.strip().str.upper()
df_1['dob_1'] = pd.to_datetime(df_1['dob'],format='%d.%m.%Y',errors='coerce') 
df_1['state/unit'] = df_1['state/unit'].str.strip().str.upper()
df_1 = df_1[['event_name','name','dob_1','state/unit']]   
df_1.rename(columns={'dob_1':'dob'}, inplace=True)

In [425]:
for _,row in df_1.iterrows():
    senior_dec_2024_player_info[row['name']].append({
        'event_name': row['event_name'],
        'dob': row['dob'],
        'state/unit': row['state/unit'],
        'name': row['name']
    })

In [426]:
df_2['event_name'] = df_2['event_name'].str.replace('MEDAL TALLY - ','').str.strip().str.upper()
df_2['name'] = df_2['name'].str.strip().str.upper()
df_2['dob'] = None
df_2['state/unit'] = df_2['state/unit'].str.strip().str.upper()
df_2 = df_2[['event_name','name','dob','state/unit']]

In [427]:
for _,row in df_2.iterrows():
    senior_dec_2024_player_info[row['name']].append({
        'event_name': row['event_name'],
        'dob': row['dob'],
        'state/unit': row['state/unit'],
        'name': row['name']
    })

# Senior 2023

In [428]:
senior_nov_2023_player_info = DefaultDict(list)

In [429]:
df_1 = pd.read_csv('Senior Nov 2023/senior_2023_players_info_v2.csv')
df_2 = pd.read_csv('Senior Nov 2023/senior_2023_players_info.csv')

In [430]:
df_1.head(3)

     event_name                         name         dob   state/unit
0  COMPOUND MEN  Prathamesh Bhalchandra Fuge  28.12.2002  Maharashtra
1  COMPOUND MEN          Ojas Pravin Deotale  18.06.2002  Maharashtra
2  COMPOUND MEN                     Priyansh  22.03.2003        Delhi

In [431]:
df_1['event_name'] = df_1['event_name'].str.replace('MEDAL TALLY - ','').str.strip().str.upper()
df_1['name'] = df_1['name'].str.strip().str.upper()
df_1['state/unit'] = df_1['state/unit'].str.strip().str.upper()
df_1['dob'] = pd.to_datetime(df_1['dob'],format='%d.%m.%Y',errors='coerce') 
df_1 = df_1[['event_name','name','dob','state/unit']]

In [432]:
for _,row in df_1.iterrows():
    senior_nov_2023_player_info[row['name']].append({
        'event_name': row['event_name'],
        'dob': row['dob'],
        'state/unit': row['state/unit'],
        'name': row['name']
    })

In [433]:
df_2['event_name'] = df_2['event_name'].str.replace('MEDAL TALLY','').str.strip().str.upper()
df_2['name'] = df_2['name'].str.strip().str.upper()
df_2['dob'] = pd.to_datetime(df_2['dob'],format='%d.%m.%Y',errors='coerce')
df_2['state/unit'] = df_2['state/unit'].str.strip().str.upper()
df_2 = df_2[['event_name','name','dob','state/unit']]

In [434]:
for _,row in df_2.iterrows():
    senior_nov_2023_player_info[row['name']].append({
        'event_name': row['event_name'],
        'dob': row['dob'],
        'state/unit': row['state/unit'],
        'name': row['name']
    })

In [435]:
senior_nov_2023_player_info,senior_dec_2024_player_info,junior_2025_player_info,junior_2023_player_info

(defaultdict(list,
             {'PRATHAMESH BHALCHANDRA FUGE': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2002-12-28 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'PRATHAMESH BHALCHANDRA FUGE'},
               {'event_name': 'COMPOUND - 50+50 MTRS DISTANCE MEN',
                'dob': Timestamp('2002-12-28 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'PRATHAMESH BHALCHANDRA FUGE'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('2002-12-28 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'PRATHAMESH BHALCHANDRA FUGE'}],
              'OJAS PRAVIN DEOTALE': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2002-06-18 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'OJAS PRAVIN DEOTALE'},
               {'event_name': 'COMPOUND - 50+50 MTRS DISTANCE MEN',
                'dob': Timestamp('2002-06-18 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'OJAS PRAVIN DEOTALE'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('2002-06-18 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'OJAS PRAVIN DEOTALE'}],
              'PRIYANSH': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-03-22 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'PRIYANSH'},
               {'event_name': 'COMPOUND - 50+50 MTRS DISTANCE MEN',
                'dob': Timestamp('2003-03-22 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'PRIYANSH'},
               {'event_name': 'COMPOUND - MIXED TEAM',
                'dob': Timestamp('2003-03-22 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'PRIYANSH'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('2003-03-22 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'PRIYANSH'}],
              'PRATHAMESH SAMADHAN JAWKAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-09-08 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'PRATHAMESH SAMADHAN JAWKAR'},
               {'event_name': 'COMPOUND - INDIVIDUAL ELIMINATION ROUND MEN',
                'dob': Timestamp('2003-09-08 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'PRATHAMESH SAMADHAN JAWKAR'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('2003-09-08 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'PRATHAMESH SAMADHAN JAWKAR'}],
              'KUNDERU VENKATADRI': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-09-28 00:00:00'),
                'state/unit': 'ANDHRA PRADESH',
                'name': 'KUNDERU VENKATADRI'}],
              'CHIRAG VIDYARTHI': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-07-15 00:00:00'),
                'state/unit': 'MADHYA PRADESH',
                'name': 'CHIRAG VIDYARTHI'}],
              'RAJAT CHAUHAN': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1994-12-30 00:00:00'),
                'state/unit': 'AIPSCB',
                'name': 'RAJAT CHAUHAN'},
               {'event_name': 'COMPOUND - INDIVIDUAL ELIMINATION ROUND MEN',
                'dob': Timestamp('1994-12-30 00:00:00'),
                'state/unit': 'AIPSCB',
                'name': 'RAJAT CHAUHAN'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('1994-12-30 00:00:00'),
                'state/unit': 'AIPSCB',
                'name': 'RAJAT CHAUHAN'}],
              'ABHISHEK VERMA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1989-06-26 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'ABHISHEK VERMA'},
               {'event_name': 'COMPOUND - INDIVIDUAL ELIMINATION ROUND MEN',
                'dob': Timestamp('1989-06-26 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'ABHISHEK VERMA'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('1989-06-26 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'ABHISHEK VERMA'}],
              'RISHABH YADAV': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2002-08-13 00:00:00'),
                'state/unit': 'HARYANA',
                'name': 'RISHABH YADAV'}],
              'HRITIK SHARMA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2002-05-19 00:00:00'),
                'state/unit': 'JAMMU & KASHMIR',
                'name': 'HRITIK SHARMA'}],
              'SACHIN CHECHI': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2007-09-25 00:00:00'),
                'state/unit': 'RAJASTHAN',
                'name': 'SACHIN CHECHI'}],
              'RITIK CHAHAL': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-10-12 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'RITIK CHAHAL'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('2003-10-12 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'RITIK CHAHAL'}],
              'SANGAMPREET SINGH BISLA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1999-02-17 00:00:00'),
                'state/unit': 'PUNJAB',
                'name': 'SANGAMPREET SINGH BISLA'},
               {'event_name': 'COMPOUND - MIXED TEAM',
                'dob': Timestamp('1999-02-17 00:00:00'),
                'state/unit': 'PUNJAB',
                'name': 'SANGAMPREET SINGH BISLA'}],
              'TEJBEER SINGH JAHAGIRDAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2004-06-17 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'TEJBEER SINGH JAHAGIRDAR'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('2004-06-17 00:00:00'),
                'state/unit': 'MAHARASHTRA',
                'name': 'TEJBEER SINGH JAHAGIRDAR'}],
              'KUSHAL DALAL': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2005-01-23 00:00:00'),
                'state/unit': 'HARYANA',
                'name': 'KUSHAL DALAL'}],
              'CHITTIBOMMA JIGNAS': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1994-01-12 00:00:00'),
                'state/unit': 'ANDHRA PRADESH',
                'name': 'CHITTIBOMMA JIGNAS'}],
              'MANABJYOTI BARMAN': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1995-10-01 00:00:00'),
                'state/unit': 'ASSAM',
                'name': 'MANABJYOTI BARMAN'}],
              'TAKHELLAMBAM ABUNGCHA SINGH': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1992-03-02 00:00:00'),
                'state/unit': 'SSCB',
                'name': 'TAKHELLAMBAM ABUNGCHA SINGH'}],
              'Y CHARAN REDDY': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1994-11-15 00:00:00'),
                'state/unit': 'RSPB',
                'name': 'Y CHARAN REDDY'}],
              'SHUBHAM DAS': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1999-07-30 00:00:00'),
                'state/unit': 'RSPB',
                'name': 'SHUBHAM DAS'}],
              'PULKIT KAJLA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-02-02 00:00:00'),
                'state/unit': 'RAJASTHAN',
                'name': 'PULKIT KAJLA'}],
              'PIYUSH JOSHI': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-02-18 00:00:00'),
                'state/unit': 'RAJASTHAN',
                'name': 'PIYUSH JOSHI'}],
              'KHYAM BAHADUR POUDEL CHHETRI': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1990-01-28 00:00:00'),
                'state/unit': 'MIZORAM',
                'name': 'KHYAM BAHADUR POUDEL CHHETRI'}],
              'LAISHRAM YOHENBA SINGH': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2004-10-02 00:00:00'),
                'state/unit': 'MANIPUR',
                'name': 'LAISHRAM YOHENBA SINGH'}],
              'PRITISH CHOWDHURY': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2021-01-09 00:00:00'),
                'state/unit': 'MADHYA PRADESH',
                'name': 'PRITISH CHOWDHURY'}],
              'SAGAR CHOPRA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1997-03-10 00:00:00'),
                'state/unit': 'RSPB',
                'name': 'SAGAR CHOPRA'}],
              'ANKIT YADAV': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2004-07-11 00:00:00'),
                'state/unit': 'RAJASTHAN',
                'name': 'ANKIT YADAV'}],
              'SAURABH PANDEY': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2000-11-13 00:00:00'),
                'state/unit': 'GOA',
                'name': 'SAURABH PANDEY'}],
              'PRINCE RAJPUT': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1996-04-29 00:00:00'),
                'state/unit': 'ESIC CSCB',
                'name': 'PRINCE RAJPUT'}],
              'BHAGWAN DAS': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1993-05-10 00:00:00'),
                'state/unit': 'AIPSCB',
                'name': 'BHAGWAN DAS'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('1993-05-10 00:00:00'),
                'state/unit': 'AIPSCB',
                'name': 'BHAGWAN DAS'}],
              'SHEKHER VAIDWAN': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1998-07-15 00:00:00'),
                'state/unit': 'SSCB',
                'name': 'SHEKHER VAIDWAN'}],
              'UDAY KAMBOJ': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-12-01 00:00:00'),
                'state/unit': 'PUNJAB',
                'name': 'UDAY KAMBOJ'}],
              'DEEPAK KUMAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-05-04 00:00:00'),
                'state/unit': 'JHARKHAND',
                'name': 'DEEPAK KUMAR'}],
              'AMIT THAKUR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2000-11-28 00:00:00'),
                'state/unit': 'JAMMU & KASHMIR',
                'name': 'AMIT THAKUR'}],
              'HARSH KUMAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2007-01-04 00:00:00'),
                'state/unit': 'CHANDIGARH',
                'name': 'HARSH KUMAR'}],
              'SAHIL BAWEJA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1996-01-03 00:00:00'),
                'state/unit': 'GOA',
                'name': 'SAHIL BAWEJA'}],
              'TANISHDEEP SINGH': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1999-09-19 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'TANISHDEEP SINGH'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('1999-09-19 00:00:00'),
                'state/unit': 'DELHI',
                'name': 'TANISHDEEP SINGH'}],
              'RAMAKANTA SHANGLAKPAM': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1994-03-01 00:00:00'),
                'state/unit': 'AIPSCB',
                'name': 'RAMAKANTA SHANGLAKPAM'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('1994-03-01 00:00:00'),
                'state/unit': 'AIPSCB',
                'name': 'RAMAKANTA SHANGLAKPAM'}],
              'PENDYALA TRINATH CHOWDARY': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2006-10-24 00:00:00'),
                'state/unit': 'ANDHRA PRADESH',
                'name': 'PENDYALA TRINATH CHOWDARY'}],
              'MUTUM BIKRAM SINGH': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1996-09-01 00:00:00'),
                'state/unit': 'MANIPUR',
                'name': 'MUTUM BIKRAM SINGH'}],
              'RAKESH KUMAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1985-01-13 00:00:00'),
                'state/unit': 'JAMMU & KASHMIR',
                'name': 'RAKESH KUMAR'}],
              'MUKESH KUMAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1990-07-19 00:00:00'),
                'state/unit': 'SSCB',
                'name': 'MUKESH KUMAR'}],
              'CHINNARAJU SRITHER': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1983-06-10 00:00:00'),
                'state/unit': 'GOA',
                'name': 'CHINNARAJU SRITHER'}],
              'G.R.SRIRAAM': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2002-09-17 00:00:00'),
                'state/unit': 'TAMILNADU',
                'name': 'G.R.SRIRAAM'}],
              'RAGAHV PATIDAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2004-12-21 00:00:00'),
                'state/unit': 'MADHYA PRADESH',
                'name': 'RAGAHV PATIDAR'}],
              'MOHIT DAGAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2008-01-26 00:00:00'),
                'state/unit': 'HARYANA',
                'name': 'MOHIT DAGAR'}],
              'AJAY SINGH SHEKHAWAT': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1996-05-02 00:00:00'),
                'state/unit': 'ESIC CSCB',
                'name': 'AJAY SINGH SHEKHAWAT'}],
              'PRAVEEN KUMAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1991-04-05 00:00:00'),
                'state/unit': 'UTTAR PRADESH',
                'name': 'PRAVEEN KUMAR'},
               {'event_name': 'COMPOUND - MIXED TEAM',
                'dob': Timestamp('1991-04-05 00:00:00'),
                'state/unit': 'UTTAR PRADESH',
                'name': 'PRAVEEN KUMAR'}],
              'KEITHELLAKPAM ROBERT SINGH': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1996-12-11 00:00:00'),
                'state/unit': 'ARUNACHAL PRADESH',
                'name': 'KEITHELLAKPAM ROBERT SINGH'}],
              'KRISH CHANDRA DEV': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2005-03-18 00:00:00'),
                'state/unit': 'JHARKHAND',
                'name': 'KRISH CHANDRA DEV'}],
              'MANJIT KUMAR': [{'event_name': 'COMPOUND MEN',
                'dob': NaT,
                'state/unit': 'PONDICHERRY',
                'name': 'MANJIT KUMAR'}],
              'SANTOSH KUMAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1985-01-05 00:00:00'),
                'state/unit': 'AIPSCB',
                'name': 'SANTOSH KUMAR'},
               {'event_name': 'INDIAN ROUND MEN',
                'dob': Timestamp('2001-04-01 00:00:00'),
                'state/unit': 'BIHAR',
                'name': 'SANTOSH KUMAR'},
               {'event_name': 'COMPOUND - TEAM EVENT MEN',
                'dob': Timestamp('1985-01-05 00:00:00'),
                'state/unit': 'AIPSCB',
                'name': 'SANTOSH KUMAR'}],
              'MOHD SHAVEJ': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2004-10-15 00:00:00'),
                'state/unit': 'UTTAR PRADESH',
                'name': 'MOHD SHAVEJ'}],
              'GURWINDER SINGH': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1994-08-15 00:00:00'),
                'state/unit': 'SSCB',
                'name': 'GURWINDER SINGH'}],
              'SUNENDU ROY': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1991-04-29 00:00:00'),
                'state/unit': 'ANDHRA PRADESH',
                'name': 'SUNENDU ROY'}],
              'BALAM SINGH KHANI': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2000-12-10 00:00:00'),
                'state/unit': 'UTTAR PRADESH',
                'name': 'BALAM SINGH KHANI'}],
              'KULDEEP SHARMA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1994-10-09 00:00:00'),
                'state/unit': 'HIMACHAL PRADESH',
                'name': 'KULDEEP SHARMA'}],
              'MOHAMMAD AAMIR KHAN': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1996-06-28 00:00:00'),
                'state/unit': 'CHHATTISGARH',
                'name': 'MOHAMMAD AAMIR KHAN'}],
              'DIBYA RANJAN MUNDA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-06-28 00:00:00'),
                'state/unit': 'ODISHA',
                'name': 'DIBYA RANJAN MUNDA'}],
              'STANZIN JIGDAL': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1999-12-14 00:00:00'),
                'state/unit': 'LADAKH',
                'name': 'STANZIN JIGDAL'}],
              'GURUMAYUM ROBERT SHARMA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1992-02-02 00:00:00'),
                'state/unit': 'MANIPUR',
                'name': 'GURUMAYUM ROBERT SHARMA'}],
              'SACHIN CHAUDHARY': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-05-12 00:00:00'),
                'state/unit': 'UTTAR PRADESH',
                'name': 'SACHIN CHAUDHARY'}],
              'MUKESHBHAI RELIYABHAI RATHVA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1987-06-01 00:00:00'),
                'state/unit': 'GUJARAT',
                'name': 'MUKESHBHAI RELIYABHAI RATHVA'}],
              'ASHISH KUMAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2001-04-01 00:00:00'),
                'state/unit': 'BIHAR',
                'name': 'ASHISH KUMAR'}],
              'BIPLAB SINGHA KARJEE': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-04-05 00:00:00'),
                'state/unit': 'WEST BENGAL',
                'name': 'BIPLAB SINGHA KARJEE'}],
              'DIGVIJAY SINGH': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2005-12-02 00:00:00'),
                'state/unit': 'UTTRAKHAND',
                'name': 'DIGVIJAY SINGH'}],
              'GURNOOR SINGH': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2005-02-23 00:00:00'),
                'state/unit': 'PUNJAB',
                'name': 'GURNOOR SINGH'}],
              'PARASHAN NATH': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1991-03-27 00:00:00'),
                'state/unit': 'ASSAM',
                'name': 'PARASHAN NATH'}],
              'HARSH SIKARWAR': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-03-09 00:00:00'),
                'state/unit': 'MADHYA PRADESH',
                'name': 'HARSH SIKARWAR'}],
              'BAKARAM RAHUL': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2003-04-03 00:00:00'),
                'state/unit': 'TELANGANA',
                'name': 'BAKARAM RAHUL'}],
              'VEMULA SHIVA SAI': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2004-02-28 00:00:00'),
                'state/unit': 'TELANGANA',
                'name': 'VEMULA SHIVA SAI'}],
              'SAGAR RAITA': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('2007-03-20 00:00:00'),
                'state/unit': 'ODISHA',
                'name': 'SAGAR RAITA'}],
              'NAVEEN': [{'event_name': 'COMPOUND MEN',
                'dob': Timestamp('1998-11-19 00:00:00'),
                'state/unit': 'CHANDIGARH',
                'name': 'NAVEEN'}],
              'AKASHDEEP': [{'event_name': 'COMPOUND MEN',

In [191]:
df = pd.read_csv("/mnt/c/Users/Ashish Maharana/Downloads/Archery Competition Data (2).csv")

In [194]:
df['championship_name'] = df['championship_name'].str.strip().str.upper()

In [195]:
df['championship_name'].unique()

<StringArray>
[                                                                                         'WORLD ARCHERY CHAMPIONSHIPS 2021',
                                                                                          'WORLD ARCHERY CHAMPIONSHIPS 2023',
                                                                                          'WORLD ARCHERY CHAMPIONSHIPS 2025',
                                                                                           'ARCHERY AT THE 2018 ASIAN GAMES',
                                                                                           'ARCHERY AT THE 2022 ASIAN GAMES',
                                                                                          'ASIAN ARCHERY CHAMPIONSHIPS 2021',
                                                                                          'ASIAN ARCHERY CHAMPIONSHIPS 2023',
                                                                                                   '37TH NATIONAL GAMES GOA',
                                                                                           '38TH NATIONAL GAMES UTTARAKHAND',
                                                                                       'ARCHERY AT THE 2016 SUMMER OLYMPICS',
                                                                                       'ARCHERY AT THE 2020 SUMMER OLYMPICS',
                                                                                       'ARCHERY AT THE 2024 SUMMER OLYMPICS',
                                   '42ND NTPC JUNIOR (RECURVE, COMPOUND & INDIAN ROUND) NATIONAL (M&W) ARCHERY CHAMPIONSHIP',
                                                                    '43RD NTPC JUNIOR NATIONAL (M & W) ARCHERY CHAMPIONSHIP',
                                                                    '44TH NTPC JUNIOR NATIONAL (M & W) ARCHERY CHAMPIONSHIP',
 '31ST NTPC SENIOR INDIAN ROUND, 44TH NTPC SENIOR RECURVE AND 20TH NTPC SENIOR COMPOUND (M&W) NATIONAL ARCHERY CHAMPIONSHIP',
 '30TH NTPC SENIOR INDIAN ROUND, 43RD NTPC SENIOR RECURVE AND 19TH NTPC SENIOR COMPOUND NATIONAL (M&W) ARCHERY CHAMPIONSHIP']
Length: 17, dtype: str

# Senior 2023 Final

In [220]:
df_1 = df[df['championship_name'] == '30TH NTPC SENIOR INDIAN ROUND, 43RD NTPC SENIOR RECURVE AND 19TH NTPC SENIOR COMPOUND NATIONAL (M&W) ARCHERY CHAMPIONSHIP']

In [221]:
## Cleaning the winner,event_name, player_b,player_a,round_name columns for the senior national championship data
df_1['winner'] = df_1['winner'].str.strip().str.upper()
df_1["winner_state"] = df_1["player_a"].str.findall(r"\(([^)]*)\)")
df_1["winner_state"] =  df_1["winner_state"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)


df_1['player_a'] = df_1['player_a'].str.strip().str.upper()
df_1["player_a_state"] = df_1["player_a"].str.findall(r"\(([^)]*)\)")
df_1["player_a_state"] =  df_1["player_a_state"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)


df_1['player_b'] = df_1['player_b'].str.strip().str.upper()
df_1["player_b_state"] = df_1["player_b"].str.findall(r"\(([^)]*)\)")
df_1["player_b_state"] =  df_1["player_b_state"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

In [222]:
df_1 = df_1.explode("player_a_state").reset_index(drop=True)
df_1 = df_1.explode("winner_state").reset_index(drop=True)
df_1 = df_1.explode("player_b_state").reset_index(drop=True)

In [223]:
df_1['player_a_state'] = df_1['player_a_state'].str.strip().str.upper() 
df_1['player_b_state'] = df_1['player_b_state'].str.strip().str.upper()
df_1['winner_state'] = df_1['winner_state'].str.strip().str.upper()

In [224]:
df_1["player_b"] = df_1["player_b"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_b"] = (
    df_1["player_b"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

df_1["player_a"] = df_1["player_a"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_a"] = (
    df_1["player_a"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)


df_1["winner"] = df_1["winner"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["winner"] = (
    df_1["winner"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

In [251]:
df_1['player_a'] = df_1['player_a'].str.split(',')
df_1['player_b'] = df_1['player_b'].str.split(',')
df_1['winner'] = df_1['winner'].str.split(',')


df_1 = df_1.explode("player_a").reset_index(drop=True)
df_1 = df_1.explode("player_b").reset_index(drop=True)
df_1 = df_1.explode("winner").reset_index(drop=True)

In [258]:
round_standardization_dict = {
    'Quarter-Final': 'QUARTER-FINAL',
    'Semi-Final': 'SEMI-FINAL',
    'Final': 'FINAL',
    '1/8 Final': '1/8 FINAL',
    '1/4 Final': '1/4 FINAL',
    'Bronze Medal': 'BRONZE MEDAL'
}

In [259]:
df_1['round_name'] = df_1['round_name'].apply(lambda x : round_standardization_dict.get(x, x))

In [269]:
def get_dob(player_name):
    for key in [senior_nov_2023_player_info, senior_dec_2024_player_info, junior_2025_player_info, junior_2023_player_info]:
        if player_name in key:
            for val in key[player_name]:
                if val['dob'] is not None:
                    return val['dob']
    return None

In [274]:
df_1['player_a'] = df_1['player_a'].str.strip().str.upper()
df_1['player_b'] = df_1['player_b'].str.strip().str.upper()
df_1['winner'] = df_1['winner'].str.strip().str.upper()

In [ ]:
player_name_standardization_dict = {
    
    'ARJUNTHAI JATARIYAHAI VASAVA':"ARJUNBHAI JATARIYABHAI VASAVA",
    'ARUN KR':"ARUN KUMAR",
    'CHITHOMMA JIGNAS':"CHITTIBOMMA JIGNAS",
    'CHULAM RASOOL':"GHULAM RASOOL",
    'KUNDERA VENKATADRI':"KUNDERU VENKATADRI",
    'LAISHRAM YOHANNA SINGH':"LAISHRAM YOHENBA SINGH",
    'LALIPHRAKPAM ROJINA SING':"LAIIPHRAKPAM ROJINA SING",
    'LOSHKAN BODRA':"LOUKHAN BODRA",
    'METUM BIKRAM SINGH':"MUTUM BIKRAM SINGH",
    'MONA KUMAR':"MONU KUMAR",
    'PRASAD RAUSHADE BHANGA':"PRASAD RAOSAHEB BHANGE",
    'RAMANDEEP KAUR':"RAMANDEEP KOUR",
    'RUKESH KUMAR':"RAKESH KUMAR",
    'SHILBHABA LAITANTHEM':"SHILBHABA LAITANTHEM",
    'SORU':"SORU",
    
    
    
    'TAHLELLAMBAM ABHUGCHA SINGH' : "TAKHELLAMBAM ABUNGCHA SINGH",
    'PRIJANSH': "PRIYANSH",
    'RUKESH KUMAR': "RAKESH KUMAR",
    'LAISHRAM YOHANNA SINGH': "LAISHRAM YOHENBA SINGH",
    'METUM BIKRAM SINGH': "MUTUM BIKRAM SINGH",
    'MADHURA DHAMANGONKAR': "MADHURA DHAMANGAONKAR",
    'MONA KUMAR': "MONU KUMAR",
    'SHILHEHA LEITANHEM': "SHILHEIBA LEITANTHEM",
    'ZHAKOTNO DEMO': "ZHOKHOTO DEMO",
    'CHUNGHAM HARICHANDRA SINGH': "CHUNGKHAM HARICHANDRA SINGH",
    'KUBER JAGAT': "KUBAR JAGAT",
    'BILARAM MAJHI': "BIKRAM MAJHI",
    'SORU': "SORU",
    'PUKHRAMBAM HEROHA SINGH': "PUKHRAMBAM HEROBA SINGH",
    'LOSHKAN BODRA': "LOUKHAN BODRA",
    'KALYANI GAIKWAD': "KALYANI GAIKWAD",
    'VARSHA SOMA': "VARSHA SONA",
    'THOHRI SANA': "THOHRII SANAI",
    
    'LALIPHRAKPAM ROJINA SING':'LAIIPHRAKPAM ROJINA SING',
    'SHILBHABA LAITANTHEM' : 'SHILHEIBA LEITANTHEM'

}

[{'event_name': 'INDIAN ROUND MEN',
  'dob': NaT,
  'state/unit': 'CHHATTISGARH',
  'name': 'KUBAR JAGAT'}]

In [324]:
df_1['player_a'] = df_1['player_a'].apply(lambda x : player_name_standardization_dict.get(x, x))
df_1['player_b'] = df_1['player_b'].apply(lambda x : player_name_standardization_dict.get(x, x))
df_1['winner'] = df_1['winner'].apply(lambda x : player_name_standardization_dict.get(x, x))

In [325]:
df_1['player_a_dob'] = df_1['player_a'].apply(lambda x : get_dob(x))
df_1['player_b_dob'] = df_1['player_b'].apply(lambda x : get_dob(x))
df_1['winner_dob'] = df_1['winner'].apply(lambda x : get_dob(x))

In [326]:
state_list = df_1[df_1['winner_dob'].isna()]['winner'].unique()

In [327]:
state_list

<StringArray>
['SORU']
Length: 1, dtype: str

In [328]:
import numpy as np

mask = (df_1['winner'].isin(state_list)) & (df_1['score_a'] > df_1['score_b'])

df_1.loc[mask, 'winner'] = np.where(
    df_1.loc[mask, 'score_a'] > df_1.loc[mask, 'score_b'],
    df_1.loc[mask, 'player_a'],
    df_1.loc[mask, 'player_b']
)

In [329]:
df_1['winner_dob'] = df_1['winner'].apply(lambda x : get_dob(x))

In [330]:
state_list = df_1[df_1['winner_dob'].isna()]['winner'].unique()

In [331]:
mask = (df_1['winner'].isin(state_list)) & (df_1['score_a'] > df_1['score_b'])
df_1.loc[mask, 'winner'] = np.where(
    df_1.loc[mask, 'score_a'] > df_1.loc[mask, 'score_b'],
    df_1.loc[mask, 'player_a'],
    df_1.loc[mask, 'player_b']
)

mask_2 = (df_1['winner'].isin(state_list)) & (df_1['score_a'] < df_1['score_b'])
df_1.loc[mask_2, 'winner'] = np.where(
    df_1.loc[mask_2, 'score_a'] < df_1.loc[mask_2, 'score_b'],
    df_1.loc[mask_2, 'player_b'],
    df_1.loc[mask_2, 'player_a']
)

In [332]:
df_1['winner_dob'] = df_1['winner'].apply(lambda x : get_dob(x))

In [334]:
df_1[df_1['player_b_dob'].isna()]['player_b'].unique()

<StringArray>
['KUBAR JAGAT', 'SORU', 'KALYANI GAIKWAD']
Length: 3, dtype: str

In [339]:
df_1[['championship_name','event_name','round_name','player_a','player_a_dob','player_a_state','score_a','player_b','player_b_dob','player_b_state','score_b','winner','winner_dob','winner_state']].to_csv('/home/ashish-1221/archery_scrapping/archercy_scrapping/results/PDFs/Senior Nov 2023/senior_nov_2023_players_cleaned.csv', index=False)

In [ ]:
df_1.to_csv('/home/ashish-1221/archery_scrapping/archercy_scrapping/results/PDFs/Senior Nov 2023/senior_nov_2023_players_cleaned.csv', index=False)

<StringArray>
[ 'PRATHAMESH BHALCHANDRA FUGE',                 'RITIK CHAHAL',
                     'PRIYANSH',                'RAJAT CHAUHAN',
               'ABHISHEK VERMA',          'OJAS PRAVIN DEOTALE',
 ' PRATHAMESH BHALCHANDRA FUGE',                'HRITIK SHARMA',
                 ' AMIT THAKUR',                ' RUKESH KUMAR',
                'RISHABH YADAV',                ' KUSHAL DALAL',
                 ' MOHIT DAGAR',       'LAISHRAM YOHANNA SINGH',
          ' METUM BIKRAM SINGH',           'KUNDERA VENKATADRI',
            ' CHITHOMMA JIGNAS',               'SAURABH PANDEY',
                ' SAHIL BAWEJA',             'CHIRAG VIDYARTHI',
           ' PRITISH CHOWDHURY',                'PRINCE RAJPUT',
        ' AJAY SINGH SHEKHAWAT',                 ' BHAGWAN DAS',
        'ADITI GOPICHAND SWAMI',                'RAGINEE MARKO',
                 'PARNEET KAUR',                      'AKSHITA',
               'AZADVEER SINGH',                'UJJWAL MUDGAL',
                  'VIKAS YADAV',        'SRABAN KUMAR MANDANGI',
           'DASARATH RAJAGOPAL',                     ' ARUN KR',
               'YOGENDRA HESSA',               ' LOSHKAN BODRA',
       'PRASAD RAUSHADE BHANGA',            ' SHUBHAM RAM NAGE',
 'ARJUNTHAI JATARIYAHAI VASAVA',            ' JAY PREMAJI BHAT',
              'MANARANJAN BORO',              ' RAJESH NARZARY',
                   'MONA KUMAR',                'CHULAM RASOOL',
                ' MOHD HUSSAIN',         'SHILBHABA LAITANTHEM',
                         'SORU',                      ' ASHISH',
     'LALIPHRAKPAM ROJINA SING',                  'MANJOT KAUR',
                'TUTUMONI BORO',               'RAMANDEEP KAUR',
                     'SANGEETA',                 'NIKKI SHARMA',
                        'RIDHI',            'AMISHA CHAURASIYA']
Length: 56, dtype: str

In [226]:
event_standardization_dict = {
    'Compound Men': 'COMPOUND MEN',
    'Compound Men Team': 'COMPOUND MEN TEAM',
    'Compound Women': 'COMPOUND WOMEN',
    'Indian Round Men': 'INDIAN ROUND MEN',
    'Indian Round Men Team': 'INDIAN ROUND MEN TEAM',
    'Indian Round Women': 'INDIAN ROUND WOMEN',
    'Recurve Women': 'RECURVE WOMEN'
}

df_1['event_name'] = df_1['event_name'].replace(event_standardization_dict).fillna(df['event_name'])

In [227]:
df_1 = df_1[['championship_name','event_name','round_name','player_a','player_a_state','score_a','player_b','player_b_state','score_b','winner','winner_state']]

In [237]:
not_found_list = []

for key,value in senior_nov_2023_player_info.items():
    if key not in df_1['player_a'].values:
        not_found_list.append(key)
    if key not in df_1['player_b'].values:
        not_found_list.append(key)
    if key not in df_1['winner'].values:
        not_found_list.append(key)

In [243]:
list_of_players = [df_1['player_a'].unique().tolist() + df_1['player_b'].unique().tolist() + df_1['winner'].unique().tolist()]

In [236]:
df_1[df_1['player_a'] == 'PRATHAMESH BHALCHANDRA FUGE']

,championship_name,event_name,round_name,player_a,player_a_state,score_a,player_b,player_b_state,score_b,winner,winner_state
0,"30TH NTPC SENIOR INDIAN ROUND, 43RD NTPC SENIO...",COMPOUND MEN,Quarter-Final,PRATHAMESH BHALCHANDRA FUGE,MAHARASHTRA,146,ABHISHEK VERMA,DELHI,148,ABHISHEK VERMA,MAHARASHTRA

# Senior 2024 Final

In [436]:
df = pd.read_csv("/mnt/c/Users/Ashish Maharana/Downloads/Archery Competition Data (2).csv")

In [437]:
df['championship_name'].unique()

<StringArray>
[                                                                                         'World Archery Championships 2021',
                                                                                          'World Archery Championships 2023',
                                                                                          'World Archery Championships 2025',
                                                                                           'Archery at the 2018 Asian Games',
                                                                                           'Archery at the 2022 Asian Games',
                                                                                          'Asian Archery Championships 2021',
                                                                                          'Asian Archery Championships 2023',
                                                                                                   '37th National Games Goa',
                                                                                           '38th National Games Uttarakhand',
                                                                                       'Archery at the 2016 Summer Olympics',
                                                                                       'Archery at the 2020 Summer Olympics',
                                                                                       'Archery at the 2024 Summer Olympics',
                                   '42nd NTPC Junior (Recurve, Compound & Indian Round) National (M&W) Archery Championship',
                                                                    '43rd NTPC Junior National (M & W) Archery Championship',
                                                                    '44th NTPC Junior National (M & W) Archery Championship',
 '31st NTPC Senior Indian Round, 44th NTPC Senior Recurve and 20th NTPC Senior Compound (M&W) National Archery Championship',
 '30th NTPC Senior Indian Round, 43rd NTPC Senior Recurve and 19th NTPC Senior Compound National (M&W) Archery Championship']
Length: 17, dtype: str

In [438]:
df_1 = df[df['championship_name'] == '31st NTPC Senior Indian Round, 44th NTPC Senior Recurve and 20th NTPC Senior Compound (M&W) National Archery Championship']

In [440]:
df_1 = df_1[['championship_name','event_name','round_name','player_a','score_a','player_b','score_b','winner']]

In [441]:
event_standardization_dict = {
    'Recurve Men' : 'RECURVE MEN',
    'Recurve Women Team' : 'RECURVE WOMEN TEAM',
    'Recurve Women' : 'RECURVE WOMEN',
    'Recurve Mix Team' : 'RECURVE MIX TEAM',
    'Compound Men' : 'COMPOUND MEN',
    'Compound Women' : 'COMPOUND WOMEN',
    'Compound Men Team' : 'COMPOUND MEN TEAM',
    'Compound Mix Team' : 'COMPOUND MIX TEAM',
    'Indian Round Men' : 'INDIAN ROUND MEN',
    'Indian Round Women' : 'INDIAN ROUND WOMEN',
    'Indian Round Women Team' : 'INDIAN ROUND WOMEN TEAM',
    'Indian Round Mix Team' : 'INDIAN ROUND MIX TEAM'
}

In [443]:
## Cleaning the winner,event_name, player_b,player_a,round_name columns for the senior national championship data
df_1['winner'] = df_1['winner'].str.strip().str.upper()
df_1["winner_state"] = df_1["player_a"].str.findall(r"\(([^)]*)\)")
df_1["winner_state"] =  df_1["winner_state"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)


df_1['player_a'] = df_1['player_a'].str.strip().str.upper()
df_1["player_a_state"] = df_1["player_a"].str.findall(r"\(([^)]*)\)")
df_1["player_a_state"] =  df_1["player_a_state"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)


df_1['player_b'] = df_1['player_b'].str.strip().str.upper()
df_1["player_b_state"] = df_1["player_b"].str.findall(r"\(([^)]*)\)")
df_1["player_b_state"] =  df_1["player_b_state"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

In [444]:
df_1 = df_1.explode("player_a_state").reset_index(drop=True)
df_1 = df_1.explode("winner_state").reset_index(drop=True)
df_1 = df_1.explode("player_b_state").reset_index(drop=True)

In [445]:
df_1['player_a_state'] = df_1['player_a_state'].str.strip().str.upper() 
df_1['player_b_state'] = df_1['player_b_state'].str.strip().str.upper()
df_1['winner_state'] = df_1['winner_state'].str.strip().str.upper()

In [446]:
df_1["player_b"] = df_1["player_b"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_b"] = (
    df_1["player_b"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

df_1["player_a"] = df_1["player_a"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_a"] = (
    df_1["player_a"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)


df_1["winner"] = df_1["winner"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["winner"] = (
    df_1["winner"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

In [447]:
df_1['player_a'] = df_1['player_a'].str.split(',')
df_1['player_b'] = df_1['player_b'].str.split(',')
df_1['winner'] = df_1['winner'].str.split(',')


df_1 = df_1.explode("player_a").reset_index(drop=True)
df_1 = df_1.explode("player_b").reset_index(drop=True)
df_1 = df_1.explode("winner").reset_index(drop=True)

In [459]:
round_standardization_dict = {
    'Quarter-Final': 'QUARTER-FINAL',
    'Semi-Final': 'SEMI-FINAL',
    'Final': 'FINAL',
    '1/8 Final': '1/8 FINAL',
    '1/4 Final': '1/4 FINAL',
    'Bronze Medal': 'BRONZE MEDAL',
    'Gold Medal Match':'GOLD MEDAL MATCH',
    'Bronze Medal Match':'BRONZE MEDAL MATCH'
    
}

In [460]:
df_1['round_name'] = df_1['round_name'].apply(lambda x : round_standardization_dict.get(x, x))

In [461]:
df_1['round_name'].unique()

<StringArray>
[   '1/8 Elimination',    '1/4 Elimination',         'SEMI-FINAL',
   'GOLD MEDAL MATCH', 'BRONZE MEDAL MATCH',      'QUARTER-FINAL',
 'Data Not Available']
Length: 7, dtype: str

In [468]:
event_standardization_dict = {
    'Compound Men': 'COMPOUND MEN',
    'Compound Men Team': 'COMPOUND MEN TEAM',
    'Compound Women': 'COMPOUND WOMEN',
    'Indian Round Men': 'INDIAN ROUND MEN',
    'Indian Round Men Team': 'INDIAN ROUND MEN TEAM',
    'Indian Round Women': 'INDIAN ROUND WOMEN',
    'Recurve Women': 'RECURVE WOMEN',
    'Compound Mix Team' : 'COMPOUND MIX TEAM',
    'Recurve Men' : 'RECURVE MEN',  
    'Recurve Women Team' : 'RECURVE WOMEN TEAM',
    'Recurve Mix Team' : 'RECURVE MIX TEAM',
    'Indian Round Women Team': 'INDIAN ROUND WOMEN TEAM',
    'Indian Round Mix Team' : 'INDIAN ROUND MIX TEAM'
}

df_1['event_name'] = df_1['event_name'].replace(event_standardization_dict).fillna(df['event_name'])

In [472]:
event_names_info = set()
for key,val in senior_dec_2024_player_info.items():
    for value in val:
        event_name = value['event_name']
        event_names_info.add(event_name)

In [474]:
df_event_names = set(df_1['event_name'].unique().tolist())

In [476]:
df_event_names

{'COMPOUND MEN',
 'COMPOUND MEN TEAM',
 'COMPOUND MIX TEAM',
 'COMPOUND WOMEN',
 'INDIAN ROUND MEN',
 'INDIAN ROUND MIX TEAM',
 'INDIAN ROUND WOMEN',
 'INDIAN ROUND WOMEN TEAM',
 'RECURVE MEN',
 'RECURVE MIX TEAM',
 'RECURVE WOMEN',
 'RECURVE WOMEN TEAM'}

In [477]:
event_names_info

{'COMPOUND (MEN)',
 'COMPOUND (WOMEN)',
 'COMPOUND 50 MTRS (OVERALL) - MEN',
 'COMPOUND 50 MTRS (OVERALL) - WOMEN',
 'COMPOUND INDIVIDUAL OLYMPIC ROUND - MEN',
 'COMPOUND INDIVIDUAL OLYMPIC ROUND - WOMEN',
 'COMPOUND MEN - TEAM',
 'COMPOUND MIXED TEAM',
 'COMPOUND WOMEN - TEAM',
 'INDIAN ROUND (MEN)',
 'INDIAN ROUND (WOMEN)',
 'INDIAN ROUND 30 MTRS - MEN',
 'INDIAN ROUND 30 MTRS - WOMEN',
 'INDIAN ROUND 50 MTRS - MEN',
 'INDIAN ROUND 50 MTRS - WOMEN',
 'INDIAN ROUND INDIVIDUAL OLYMPIC ROUND - MEN',
 'INDIAN ROUND INDIVIDUAL OLYMPIC ROUND - WOMEN',
 'INDIAN ROUND MEN - TEAM',
 'INDIAN ROUND MIXED TEAM',
 'INDIAN ROUND WOMEN - TEAM',
 'RECURVE (MEN)',
 'RECURVE (WOMEN)',
 'RECURVE 70 MTRS (OVERALL) - MEN',
 'RECURVE 70 MTRS (OVERALL) - WOMEN',
 'RECURVE INDIVIDUAL OLYMPIC ROUND - MEN',
 'RECURVE INDIVIDUAL OLYMPIC ROUND - WOMEN',
 'RECURVE MEN - TEAM',
 'RECURVE MIXED TEAM',
 'RECURVE WOMEN - TEAM'}

In [473]:
event_names_info, df_1['event_name'].unique()

({'COMPOUND (MEN)',
  'COMPOUND (WOMEN)',
  'COMPOUND 50 MTRS (OVERALL) - MEN',
  'COMPOUND 50 MTRS (OVERALL) - WOMEN',
  'COMPOUND INDIVIDUAL OLYMPIC ROUND - MEN',
  'COMPOUND INDIVIDUAL OLYMPIC ROUND - WOMEN',
  'COMPOUND MEN - TEAM',
  'COMPOUND MIXED TEAM',
  'COMPOUND WOMEN - TEAM',
  'INDIAN ROUND (MEN)',
  'INDIAN ROUND (WOMEN)',
  'INDIAN ROUND 30 MTRS - MEN',
  'INDIAN ROUND 30 MTRS - WOMEN',
  'INDIAN ROUND 50 MTRS - MEN',
  'INDIAN ROUND 50 MTRS - WOMEN',
  'INDIAN ROUND INDIVIDUAL OLYMPIC ROUND - MEN',
  'INDIAN ROUND INDIVIDUAL OLYMPIC ROUND - WOMEN',
  'INDIAN ROUND MEN - TEAM',
  'INDIAN ROUND MIXED TEAM',
  'INDIAN ROUND WOMEN - TEAM',
  'RECURVE (MEN)',
  'RECURVE (WOMEN)',
  'RECURVE 70 MTRS (OVERALL) - MEN',
  'RECURVE 70 MTRS (OVERALL) - WOMEN',
  'RECURVE INDIVIDUAL OLYMPIC ROUND - MEN',
  'RECURVE INDIVIDUAL OLYMPIC ROUND - WOMEN',
  'RECURVE MEN - TEAM',
  'RECURVE MIXED TEAM',
  'RECURVE WOMEN - TEAM'},
 <StringArray>
 [            'RECURVE MEN',      'RECURVE WOMEN TEAM',
            'RECURVE WOMEN',        'RECURVE MIX TEAM',
             'COMPOUND MEN',          'COMPOUND WOMEN',
        'COMPOUND MEN TEAM',       'COMPOUND MIX TEAM',
         'INDIAN ROUND MEN',      'INDIAN ROUND WOMEN',
  'INDIAN ROUND WOMEN TEAM',   'INDIAN ROUND MIX TEAM']
 Length: 12, dtype: str)

In [ ]:
df

In [ ]:
def get_dob(player_name):
    for key in [senior_nov_2023_player_info, senior_dec_2024_player_info, junior_2025_player_info, junior_2023_player_info]:
        if player_name in key:
            for val in key[player_name]:
                if val['dob'] is not None:
                    return val['dob']
    return None

In [ ]:
df_1['player_a'] = df_1['player_a'].str.strip().str.upper()
df_1['player_b'] = df_1['player_b'].str.strip().str.upper()
df_1['winner'] = df_1['winner'].str.strip().str.upper()

In [ ]:
player_name_standardization_dict = {
    
    'ARJUNTHAI JATARIYAHAI VASAVA':"ARJUNBHAI JATARIYABHAI VASAVA",
    'ARUN KR':"ARUN KUMAR",
    'CHITHOMMA JIGNAS':"CHITTIBOMMA JIGNAS",
    'CHULAM RASOOL':"GHULAM RASOOL",
    'KUNDERA VENKATADRI':"KUNDERU VENKATADRI",
    'LAISHRAM YOHANNA SINGH':"LAISHRAM YOHENBA SINGH",
    'LALIPHRAKPAM ROJINA SING':"LAIIPHRAKPAM ROJINA SING",
    'LOSHKAN BODRA':"LOUKHAN BODRA",
    'METUM BIKRAM SINGH':"MUTUM BIKRAM SINGH",
    'MONA KUMAR':"MONU KUMAR",
    'PRASAD RAUSHADE BHANGA':"PRASAD RAOSAHEB BHANGE",
    'RAMANDEEP KAUR':"RAMANDEEP KOUR",
    'RUKESH KUMAR':"RAKESH KUMAR",
    'SHILBHABA LAITANTHEM':"SHILBHABA LAITANTHEM",
    'SORU':"SORU",
    
    
    
    'TAHLELLAMBAM ABHUGCHA SINGH' : "TAKHELLAMBAM ABUNGCHA SINGH",
    'PRIJANSH': "PRIYANSH",
    'RUKESH KUMAR': "RAKESH KUMAR",
    'LAISHRAM YOHANNA SINGH': "LAISHRAM YOHENBA SINGH",
    'METUM BIKRAM SINGH': "MUTUM BIKRAM SINGH",
    'MADHURA DHAMANGONKAR': "MADHURA DHAMANGAONKAR",
    'MONA KUMAR': "MONU KUMAR",
    'SHILHEHA LEITANHEM': "SHILHEIBA LEITANTHEM",
    'ZHAKOTNO DEMO': "ZHOKHOTO DEMO",
    'CHUNGHAM HARICHANDRA SINGH': "CHUNGKHAM HARICHANDRA SINGH",
    'KUBER JAGAT': "KUBAR JAGAT",
    'BILARAM MAJHI': "BIKRAM MAJHI",
    'SORU': "SORU",
    'PUKHRAMBAM HEROHA SINGH': "PUKHRAMBAM HEROBA SINGH",
    'LOSHKAN BODRA': "LOUKHAN BODRA",
    'KALYANI GAIKWAD': "KALYANI GAIKWAD",
    'VARSHA SOMA': "VARSHA SONA",
    'THOHRI SANA': "THOHRII SANAI",
    
    'LALIPHRAKPAM ROJINA SING':'LAIIPHRAKPAM ROJINA SING',
    'SHILBHABA LAITANTHEM' : 'SHILHEIBA LEITANTHEM'

}

[{'event_name': 'INDIAN ROUND MEN',
  'dob': NaT,
  'state/unit': 'CHHATTISGARH',
  'name': 'KUBAR JAGAT'}]

In [ ]:
df_1['player_a'] = df_1['player_a'].apply(lambda x : player_name_standardization_dict.get(x, x))
df_1['player_b'] = df_1['player_b'].apply(lambda x : player_name_standardization_dict.get(x, x))
df_1['winner'] = df_1['winner'].apply(lambda x : player_name_standardization_dict.get(x, x))

In [ ]:
df_1['player_a_dob'] = df_1['player_a'].apply(lambda x : get_dob(x))
df_1['player_b_dob'] = df_1['player_b'].apply(lambda x : get_dob(x))
df_1['winner_dob'] = df_1['winner'].apply(lambda x : get_dob(x))

In [ ]:
state_list = df_1[df_1['winner_dob'].isna()]['winner'].unique()

In [ ]:
state_list

<StringArray>
['SORU']
Length: 1, dtype: str

In [ ]:
import numpy as np

mask = (df_1['winner'].isin(state_list)) & (df_1['score_a'] > df_1['score_b'])

df_1.loc[mask, 'winner'] = np.where(
    df_1.loc[mask, 'score_a'] > df_1.loc[mask, 'score_b'],
    df_1.loc[mask, 'player_a'],
    df_1.loc[mask, 'player_b']
)

In [ ]:
df_1['winner_dob'] = df_1['winner'].apply(lambda x : get_dob(x))

In [ ]:
state_list = df_1[df_1['winner_dob'].isna()]['winner'].unique()

In [ ]:
mask = (df_1['winner'].isin(state_list)) & (df_1['score_a'] > df_1['score_b'])
df_1.loc[mask, 'winner'] = np.where(
    df_1.loc[mask, 'score_a'] > df_1.loc[mask, 'score_b'],
    df_1.loc[mask, 'player_a'],
    df_1.loc[mask, 'player_b']
)

mask_2 = (df_1['winner'].isin(state_list)) & (df_1['score_a'] < df_1['score_b'])
df_1.loc[mask_2, 'winner'] = np.where(
    df_1.loc[mask_2, 'score_a'] < df_1.loc[mask_2, 'score_b'],
    df_1.loc[mask_2, 'player_b'],
    df_1.loc[mask_2, 'player_a']
)

In [ ]:
df_1['winner_dob'] = df_1['winner'].apply(lambda x : get_dob(x))

In [ ]:
df_1[df_1['player_b_dob'].isna()]['player_b'].unique()

<StringArray>
['KUBAR JAGAT', 'SORU', 'KALYANI GAIKWAD']
Length: 3, dtype: str

In [ ]:
df_1[['championship_name','event_name','round_name','player_a','player_a_dob','player_a_state','score_a','player_b','player_b_dob','player_b_state','score_b','winner','winner_dob','winner_state']].to_csv('/home/ashish-1221/archery_scrapping/archercy_scrapping/results/PDFs/Senior Nov 2023/senior_nov_2023_players_cleaned.csv', index=False)

In [ ]:
df_1.to_csv('/home/ashish-1221/archery_scrapping/archercy_scrapping/results/PDFs/Senior Nov 2023/senior_nov_2023_players_cleaned.csv', index=False)

<StringArray>
[ 'PRATHAMESH BHALCHANDRA FUGE',                 'RITIK CHAHAL',
                     'PRIYANSH',                'RAJAT CHAUHAN',
               'ABHISHEK VERMA',          'OJAS PRAVIN DEOTALE',
 ' PRATHAMESH BHALCHANDRA FUGE',                'HRITIK SHARMA',
                 ' AMIT THAKUR',                ' RUKESH KUMAR',
                'RISHABH YADAV',                ' KUSHAL DALAL',
                 ' MOHIT DAGAR',       'LAISHRAM YOHANNA SINGH',
          ' METUM BIKRAM SINGH',           'KUNDERA VENKATADRI',
            ' CHITHOMMA JIGNAS',               'SAURABH PANDEY',
                ' SAHIL BAWEJA',             'CHIRAG VIDYARTHI',
           ' PRITISH CHOWDHURY',                'PRINCE RAJPUT',
        ' AJAY SINGH SHEKHAWAT',                 ' BHAGWAN DAS',
        'ADITI GOPICHAND SWAMI',                'RAGINEE MARKO',
                 'PARNEET KAUR',                      'AKSHITA',
               'AZADVEER SINGH',                'UJJWAL MUDGAL',
                  'VIKAS YADAV',        'SRABAN KUMAR MANDANGI',
           'DASARATH RAJAGOPAL',                     ' ARUN KR',
               'YOGENDRA HESSA',               ' LOSHKAN BODRA',
       'PRASAD RAUSHADE BHANGA',            ' SHUBHAM RAM NAGE',
 'ARJUNTHAI JATARIYAHAI VASAVA',            ' JAY PREMAJI BHAT',
              'MANARANJAN BORO',              ' RAJESH NARZARY',
                   'MONA KUMAR',                'CHULAM RASOOL',
                ' MOHD HUSSAIN',         'SHILBHABA LAITANTHEM',
                         'SORU',                      ' ASHISH',
     'LALIPHRAKPAM ROJINA SING',                  'MANJOT KAUR',
                'TUTUMONI BORO',               'RAMANDEEP KAUR',
                     'SANGEETA',                 'NIKKI SHARMA',
                        'RIDHI',            'AMISHA CHAURASIYA']
Length: 56, dtype: str

In [ ]:
df_1 = df_1[['championship_name','event_name','round_name','player_a','player_a_state','score_a','player_b','player_b_state','score_b','winner','winner_state']]

In [ ]:
not_found_list = []

for key,value in senior_nov_2023_player_info.items():
    if key not in df_1['player_a'].values:
        not_found_list.append(key)
    if key not in df_1['player_b'].values:
        not_found_list.append(key)
    if key not in df_1['winner'].values:
        not_found_list.append(key)

In [ ]:
list_of_players = [df_1['player_a'].unique().tolist() + df_1['player_b'].unique().tolist() + df_1['winner'].unique().tolist()]

In [ ]:
df_1[df_1['player_a'] == 'PRATHAMESH BHALCHANDRA FUGE']

,championship_name,event_name,round_name,player_a,player_a_state,score_a,player_b,player_b_state,score_b,winner,winner_state
0,"30TH NTPC SENIOR INDIAN ROUND, 43RD NTPC SENIO...",COMPOUND MEN,Quarter-Final,PRATHAMESH BHALCHANDRA FUGE,MAHARASHTRA,146,ABHISHEK VERMA,DELHI,148,ABHISHEK VERMA,MAHARASHTRA